apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-code-pvc
  namespace: ailink-debot
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 1Gi
