spec:
  template:
    spec:
      containers:
        - name: backend
          volumeMounts:
            - name: code-nfs
              mountPath: /app/fastapi_sqlalchemy/main.py
              $patch: delete