"""empty message

Revision ID: 76cad092eefe
Revises:
Create Date: 2024-03-11 14:13:57.838683

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76cad092eefe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trees',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('energy', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('trees')
    # ### end Alembic commands ###
